In [1]:
import pandas as pd

In [22]:
df = pd.read_csv('train.csv')

# 1. How big is the data?

In [23]:
df.shape

(891, 12)

# 2. How does the data look like?

In [24]:
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
668,669,0,3,"Cook, Mr. Jacob",male,43.0,0,0,A/5 3536,8.0500,NaN,S
404,405,0,3,"Oreskovic, Miss. Marija",female,20.0,0,0,315096,8.6625,NaN,S
441,442,0,3,"Hampe, Mr. Leon",male,20.0,0,0,345769,9.5000,NaN,S
187,188,1,1,"Romaine, Mr. Charles Hallace (""Mr C Rolmane"")",male,45.0,0,0,111428,26.5500,NaN,S

# 3. What is the data type of cols?

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

# 4. Are there any missing values?

In [26]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

# 5. How does the data look mathematically?

In [27]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

# 6. Are there duplicate values?

In [28]:
df.duplicated().sum()

np.int64(0)

# 7. How is the correlation between cols?

In [29]:
df.drop(['PassengerId','Name','Parch','Ticket','Cabin'],inplace=True,axis=1)

In [30]:
df.head()

   Survived  Pclass     Sex   Age  SibSp     Fare Embarked
0         0       3    male  22.0      1   7.2500        S
1         1       1  female  38.0      1  71.2833        C
2         1       3  female  26.0      0   7.9250        S
3         1       1  female  35.0      1  53.1000        S
4         0       3    male  35.0      0   8.0500        S

In [33]:
df['Sex']=df['Sex'].map({'male':0,'female':1})
df

     Survived  Pclass  Sex   Age  SibSp     Fare Embarked
0           0       3    0  22.0      1   7.2500        S
1           1       1    1  38.0      1  71.2833        C
2           1       3    1  26.0      0   7.9250        S
3           1       1    1  35.0      1  53.1000        S
4           0       3    0  35.0      0   8.0500        S
..        ...     ...  ...   ...    ...      ...      ...
886         0       2    0  27.0      0  13.0000        S
887         1       1    1  19.0      0  30.0000        S
888         0       3    1   NaN      1  23.4500        S
889         1       1    0  26.0      0  30.0000        C
890         0       3    0  32.0      0   7.7500        Q

[891 rows x 7 columns]

In [36]:
df["Embarked"]=df['Embarked'].map({"S":0,"C":1,"Q":2})

In [37]:
df.corr()['Survived']

Survived    1.000000
Pclass     -0.338481
Sex         0.543351
Age        -0.077221
SibSp      -0.035322
Fare        0.257307
Embarked    0.108669
Name: Survived, dtype: float64